blog/urls.py
from django.contrib.sitemaps.views import sitemap
from . import views
from django.urls import path,include
from .feeds import LatestPostFeed
from oursite.sitemaps import PostSitemap
from django.conf.urls.static import static

# Sitemap configuration
sitemaps = {
    "posts": PostSitemap,
}

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('search/', views.search, name='search'),
    path('nossa_missao/', views.NossaMissaoView.as_view(), name='nossa_missao'),
    path('sobre/', views.Sobre.as_view(), name='sobre'),
    path('contato/', views.ContatoCreate.as_view(), name='contato_form'),
    path('sucesso/', views.ContatoCreateSuccess.as_view(), name='contato_form_success'),
    path('summernote/', include('django_summernote.urls')),
    path('feed/rss',LatestPostFeed(), name='post_feed'),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path('cadastro/', views.cadastro_autor, name='cadastro_autor'),
    path('login/', views.login_autor, name='login_autor'),
    path('logado/', views.autor_logado, name='autor_logado'),
    path('logout/', views.logout_autor, name='logout_autor'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
]

oursite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap #Sitemap view
from oursite.sitemaps import PostSitemap   #Sitemap view
from django.conf import settings #Import settings module to managing media files   
from django.conf.urls.static import static #Import static module  to managing media files 



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime
from django.utils.html import format_html


# Criar nossas models aqui.

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    image = models.ImageField(upload_to='images', verbose_name='imagem',  default='images/default.jpg')
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    
    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("post_detail", kwargs={"slug": str(self.slug)})

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=200, verbose_name='nome')
    email = models.EmailField(verbose_name='email')
    body = models.TextField(verbose_name='comentário')
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)
    
class Contato(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100)
    data = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(verbose_name='email')
    telefone = models.CharField(max_length=30)
    assunto = models.CharField(max_length=100)
    mensagem = models.TextField(verbose_name='deixe sua mensagem')

    class Meta:
        verbose_name = 'Contato'
        ordering = ['-data']
        
    def __str__(self):
        return self.nome
    
class Autor(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    senha = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

blog/forms.py
from .models import Comment, Contato, Autor, Post
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

class SomeForm(forms.Form):
    foo = forms.CharField(widget=SummernoteWidget())  # instead of forms.Textarea

class AnotherForm(forms.Form):
    bar = forms.CharField(widget=SummernoteInplaceWidget())

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

# Apply summernote to specific fields.

class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato
        exclude = ('id', 'data')


class AutorForm(forms.ModelForm):
    senha = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Autor
        fields = ['nome', 'email', 'senha']

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'title', 'slug', 'content']

blog/views.py
# Crear noosas views aqui.
from django.views import generic
from .models import Post, Contato, Autor
from .forms import CommentForm , ContatoForm, AutorForm, PostForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from django.contrib.auth import logout
from django.contrib import messages 

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 3


def post_detail(request, slug):
    template_name = 'post_detail.html'
    post = Post.objects.get(slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = CommentForm()
    
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = post.comments.create(**comment_form.cleaned_data)

    return render(request, template_name, {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
    })
    
def search(request):
    query = request.GET.get('q')
    results = Post.objects.filter(Q(title__icontains=query) | Q(content__icontains=query))
    return render(request, 'search_results.html', {'results': results})

@require_POST
def post_comment(request, slug):
    post = Post.objects.get(slug)
    comment_form = CommentForm(data=request.POST)
    if comment_form.is_valid():
        post.comments.create(**comment_form.cleaned_data)
    return redirect('post_detail', slug=slug)


class ContatoCreate(CreateView):
    form_class = ContatoForm
    template_name = 'contato.html'

    
    def get_success_url(self):
        return reverse('contato_form_success')

class ContatoCreateSuccess(TemplateView):
    template_name = 'contato_success.html'


class NossaMissaoView(TemplateView):
    template_name = 'nossa_missao.html'
    

class Sobre(TemplateView):
    template_name = 'sobre.html'


def cadastro_autor(request):
    if request.method == 'POST':
        form = AutorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login_autor')  # Redireciona para a página de login
    else:
        form = AutorForm()
    return render(request, 'cadastro_autor.html', {'form': form})

def login_autor(request):
    if request.method == 'POST' and 'email' in request.POST:
        email = request.POST['email'].strip()
        senha = request.POST['senha'].strip()
       
        autor = Autor.objects.filter(email=email, senha=senha).first()
        if autor is not None:
            return redirect('autor_logado')
        else:
            return render(request, 'login_autor.html', {'erro': True})
    else:
        return render(request, 'login_autor.html')
    
def autor_logado(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
        # Save the post instance with the logged-in author
            post = form.save(commit=False)  # Don't commit yet
            post.author = request.user  # Assign the logged-in author
            post.save()  # Now save the post with the author
            return redirect('autor_logado')
    else:
        form = PostForm()
    return render(request, 'autor_logado.html', {'form': form})

def logout_autor(request):
    logout(request)
    return redirect('home')

blog/templates/autor_logado.html
{% extends 'base.html' %}
{% block content %}
<style>
    .btn-danger {
        background-color: #cd33e1;
    }
</style>
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header" style="background-color: #cd33e1; color: white;">
                    <h2 class="text-center font-weight-bold mb-0">
                        Bem-vindo(a), {{ nome_autor }}!</h2><br>
                    <h3 class="text-center font-weight-bold mb-0">
                        Contribua conosco, faça aqui a sua publicação.</h3>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-success" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_title">Título:</label>
                            <input type="text" id="id_title" name="title" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="id_slug">Slug:</label>
                            <input type="text" id="id_slug" name="slug" class="form-control" required>
                          </div>
                        <div class="form-group">
                            <label for="id_content">Conteúdo:</label>
                            <textarea id="id_content" name="content" class="form-control" rows="4" required></textarea>
                        </div>
                        <div class="form-group">
                            <label for="id_image">Imagem:</label>
                            <input type="file" id="id_image" name="image" class="form-control-file" accept="image/*">
                        </div>
                        <button type="submit" class="btn btn-danger">Adicionar Postagem</button>
                    </form>
                    <form action="{% url 'logout_autor' %}" method="post">
                        {% csrf_token %}    
                        <button type="submit" class="btn btn-primary mt-3">Logout</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center font-weight-bold mb-0">Postagens</h3>
                </div>
                <div class="card-body">
                    {% for post in posts %}
                    <div class="mb-3">
                        <h4>{{ post.title }}</h4>
                        <!-- Verifique se post.slug não está vazio e passe-o para a URL reversa -->
                        {% if post.slug %}
                            <a href="{% url 'post_detail' slug=post.slug %}" class="btn-sm btn-danger">Detalhes</a>
                        {% else %}
                            <p>Erro: o slug está vazio para esta postagem.</p>
                        {% endif %}
                    </div>
                    {% empty %}
                    <p>Nenhuma postagem encontrada.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
  <html>
    <head>
      <meta charset="UTF-8" />
      <title>Django - Squad Grace Hopper</title>
      <link
        href="https://fonts.googleapis.com/css?family=Roboto:400,700"
        rel="stylesheet"
      />
      <meta name="author" content="Squad Grace-Hopper" />
      <meta
        name="description"
        content="Projeto final do Bootcamp de Django da WoMakersCode"
      />
      <meta name="keywords" content="womakerscode,django,blog, notícias" />
      <meta name="robots" content="index,follow" />
      <meta name="google" content="notranslate" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous"
      />
      <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
      ></script>
    </head>

    <body>
      <style>
        body {
          font-family: "Roboto", sans-serif;
          font-size: 17px;
          background-color: #fdfdfd;
        }
        .shadow {
          box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
          color: #fff;
          background-color: #f00000;
          border-color: #dc281e;
        }
        .masthead {
          background: #cd33e1;
          height: auto;
          padding-bottom: 15px;
          box-shadow: 0 16px 48px #e3e7eb;
          padding-top: 10px;
        }
        .scroll-to-top {
            position: fixed;
            left: 10px;
            bottom: 15px;
            display: none;
            width: 60px;
            height: 60px;
            border: none;
            border-radius: 50%;
            background-color: #cd33e1;
            color: #fff;
            font-size: 12px;
            line-height: 1;
            text-align: center;
            cursor: pointer;
            z-index: 9999;
        }
        .scroll-to-top:hover {
            background-color: #c57fcf;
        }

        .btn-danger {
        background-color: #cd33e1;
    }
      </style>

      <!-- Navegação -->
      <nav
        class="navbar navbar-expand-lg navbar-light bg-light shadow"
        id="mainNav"
      >
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}"style="color: #cd33e1;"><strong>Squad Grace Hopper</strong></a>
          
          <button
            class="navbar-toggler navbar-toggler-right"
            type="button"
            data-toggle="collapse"
            data-target="#navbarResponsive"
            aria-controls="navbarResponsive"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <!-- barra de busca -->
          <form
            class="form-inline my-2 my-lg-0"
            action="{% url 'search' %}"
            method="get"
          >
            <input
              class="form-control mr-sm-2"
              type="buscar"
              placeholder="Buscar"
              aria-label="Buscar"
              name="q"
            />
            <button class="btn btn-danger my-2 my-sm-0" type="submit">
              Buscar
            </button>
          </form>

          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item text-black">
                <a class="nav-link text-black font-weight-bold" href="{% url 'sobre' %}"
                  >Sobre</a
                >
              </li>
              <li class="nav-item text-black">
                <a class="nav-link text-black font-weight-bold" href="{% url 'nossa_missao' %}"  
                  >Nossa missão</a
                >
              </li>
              <li class="nav-item text-black">
                <a class="nav-link text-black font-weight-bold" href="{%url 'contato_form'%}"
                  >Contato</a
                >
              </li>
            </li>
            <li class="nav-item text-black">
              <a class="nav-link text-black font-weight-bold" href="{%url 'cadastro_autor'%}"
                >Cadastre-se</a
              >
            </li>
              <li class="nav-item text-black">
                <a class="nav-link text-black font-weight-bold" href="{%url 'login_autor'%}"
                  >Login</a
                >
              </li>
            </ul>
          </div>
        </div>
      </nav>
      {% block content %}
      <!-- O conteúdo vai aqui -->
      {% endblock content %}
      <!-- Botao voltar ao topo -->
      <button class="scroll-to-top" aria-label="Voltar ao topo">
        <i class="fas fa-arrow-up"></i> Voltar ao topo
      </button>
      <!-- Footer -->
      <footer class="py-3 bg-grey">
        <p class="m-0 text-dark text-center">
          Django &#10084; Squad Grace Hopper
        </p>
      </footer>
      <!-- Bootstrap JS e jQuery (necessário para o scroll suave) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <script>
        // Adiciona o comportamento de rolagem suave ao botão "bottom of page"
        $(document).ready(function() {
            $(window).scroll(function() {
                if ($(this).scrollTop() > 100) {
                    $('.scroll-to-top').fadeIn();
                } else {
                    $('.scroll-to-top').fadeOut();
                }
            });

            $('.scroll-to-top').click(function() {
                $('html, body').animate({ scrollTop: 0 }, 'slow');
                return false;
            });
        });
    </script>
    </body>
  </html>
</html>

blog/templates/cadastro_autor.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
<style>
    .btn-danger {
        background-color: #cd33e1;
    }
</style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8" style="margin-top: 16px;">
            <div class="card">
                <div class="card-header" style="background-color: #cd33e1; color: white;">
                    <h2 class="text-center font-weight-bold">
                        Seja um de nossos autores!! <br>
                        Cadastre-se e contribua com o nosso blog:
                    </h2>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button type="submit" class="btn btn-danger mt-4">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/contato.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
<style>
    .btn-danger {
        background-color: #cd33e1;
    }
</style>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
<script>
    $(document).ready(function() {
        $('#id_telefone').mask('(00) 00000-0000');
    });
    </script>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8" style="margin-top: 16px;">
            <div class="card">
                <div class="card-header" style="background-color: #cd33e1; color: white;">
                    <h2 class="text-center font-weight-bold">Procurando mais informações? <br>Entre em contato conosco:</h2>
                </div>
                    <div class="card-body">
                    <form action="" method="post" class="mt-4">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_nome">Nome Completo</label>
                            <input type="text" name="nome" id="id_nome" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="id_email">Email</label>
                            <input type="email" name="email" id="id_email" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="id_telefone">Telefone</label>
                            <input type="text" name="telefone" id="id_telefone" class="form-control" data-mask="(00) 00000-0000">
                        </div>
                        <div class="form-group">
                            <label for="id_assunto">Assunto</label>
                            <input type="text" name="assunto" id="id_assunto" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="id_mensagem">Mensagem</label>
                            <textarea class="form-control" name="mensagem" id="id_mensagem"></textarea>
                        </div>
                        <button type="submit" class="btn btn-danger">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/contato_success.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
<style>
    .custom-card-header {
        background-color: #cd33e1;
        color: white;
    }
</style>

<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-8 text-center">
            <div class="card">
                <div class="card-header custom-card-header"><h3>SUA MENSAGEM FOI ENVIADA COM SUCESSO!</h3></div>
                <div class="card-body">
                    <p>Em breve entraremos em contato!</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/index.html
{% extends "base.html" %}
{% block content %}

<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }

    .btn-primary{
        background-color: #cd33e1;
    }

    .img {
        max-width: 100%;
        height: auto;
        margin-bottom: 12px;
        border-radius: 6px;
    }

    #page-bar {
        justify-content: center;
        align-items: center;
    }

    #header_title {
        font-weight: bold;
        font-size: 30px;
    }
    
    .pagination .page-item.active .page-link {
    background-color: #cd33e1;
    border-color: #cd33e1;
    color: #fff
    }

    .pagination .page-item .page-link {
    color: #cd33e1;
    }

    .pagination .page-item .page-link:hover {
    background-color: #e0c3ff;
    border-color: #e0c3ff;
    color: #fff;
    }

</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <div class="site-heading">
                    <h3 class="site-heading my-4 mt-3 text-white" id="header_title"> Bem-vindo ao Blog de Notícias</h3>
                    <p class="text-light">Nosso desafio final da WoMakersCode com Django!
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 mx-auto">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    {% if post.image %}
                        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img"/>
                    {% endif %}
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{ post.content | truncatechars:200 | safe }}</p> 
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Saiba Mais &rarr;</a>
                </div>
            </div>
            {% endfor %}
            <div class="pagination" id="page-bar">
                <ul class="pagination">
                    {% if is_paginated %}
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#">Previous</a>
                            </li>
                        {% endif %}
                        {% for i in page_obj.paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-item active">
                                    <a class="page-link" href="#">{{ i }}</a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#">Next</a>
                            </li>
                        {% endif %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
{%endblock%}

blog/templates/login_autor.html
{% extends 'base.html' %}
{% block content %}
<style>
    .btn-danger {
        background-color: #cd33e1;
    }
</style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8" style="margin-top: 16px;">
            <div class="card">
                <div class="card-header" style="background-color: #cd33e1; color: white;">
                    <h2 class="text-center font-weight-bold">Faça o seu login!</h2>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% if erro %}
                            <p class="alert alert-danger">Erro: email ou senha inválidos.</p>
                        {% endif %}
                        <div class="form-group">
                            <label for="email">E-mail</label>
                            <input type="email" name="email" id="email" class="form-control" placeholder="Email" required>
                        </div>
                        <div class="form-group">
                            <label for="senha">Senha</label>
                            <input type="password" name="senha" id="senha" class="form-control" placeholder="Senha" required>
                        </div>
                        <button type="submit" class="btn btn-danger">Entrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/nossa_missao.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8" style="margin-top: 16px;">
        <div class="card">
            <div class="card-header" style="background-color: #cd33e1; color: white;">
            <h2 class="text-center font-weight-bold">Nossa Missão: <br> Empoderando Mulheres na Tecnologia</h2>
          </div>
          <div class="card-body text-justify">
            <p>
                Somos um grupo de mulheres apaixonadas pelo universo da tecnologia. Algumas de nós já estão consolidadas no mercado de trabalho, outras estão dando os primeiros passos em suas carreiras, e muitas estão em transição, buscando novos desafios e oportunidades. Mas, independentemente do ponto em que nos encontramos, compartilhamos os mesmos objetivos e valores. </p>
            <p>
                Nosso propósito é tornar o mercado da tecnologia mais diverso, inclusivo e acolhedor. Acreditamos que a diversidade é a chave para a inovação e o progresso. Queremos ocupar nossos espaços, não apenas como profissionais competentes, mas como agentes de mudança que promovem a igualdade de oportunidades para todos. </p>
            <p>
                Além de profissionais de TI, somos também mães, esposas, filhas, e mulheres com sonhos e ambições. Reconhecemos a importância de equilibrar nossa vida pessoal e profissional, e buscamos na tecnologia não apenas uma carreira, mas uma ferramenta para trazer um diferencial positivo para as comunidades que nos cercam. </p>
            <p>
                Nossa abordagem é pautada pela empatia e pelo desejo genuíno de ajudar o próximo. Estamos sempre dispostas a compartilhar conhecimento, apoiar umas às outras e criar um ambiente colaborativo e inspirador. Acreditamos que juntas podemos construir um futuro melhor, onde a diversidade seja celebrada e todos tenham a oportunidade de prosperar.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}